### ISSUE TITLE
pointing-out

### ISSUE THREAD

**Issue by just-hms** [just-purple/brownies#6]
## Introduction

copy paste the code from #5 

## Exercise

- [x] create a method `Inc` which accepts no parameter and increments all the value inside of the `storage` by 1
- [x] create a method `Take` which takes the element at the specified index
    - it takes an integer named `position` and an integer named `taken` by reference
    - it returns :warning: __only an error__ which is not nil if the specified position does not exists

- [x] create a method `Add` which accepts an integers and adds it to the storage
- [x] create a method `Remove` which remove the element at the specified index
    - it takes an integer named `position`
    - it returns :warning: __only an error__ which is not nil if the specified position does not exists

- [x] create a method `FunkyReduce` which
    - add to each number in `even` position the following number (in `odd`position) 
    - then remove each number in `odd` position
    
        ex:
        ```
        [ 1 4 5 29 10 -2 ]
        ```
        res:
        ```
        [ 5 34 8 ]
        ```
        
    - if the last number is `even` leave it like it is 
 ---
 
- [x] :bulb: in the main print the storage before and after calling `Inc`, `Add`, `Reduce`, `Remove`
- [x] try to call `Dump` at the end of the main to see if everything sums up
- [x] :bulb: write the down the difference between passing an argument by value and by reference

**Comment by just-purple** [comment]
ciao
